"""Demo dataset: a small product company ("Lumen Labs") and a handful of fully processed meetings.

Transcript lines are (speaker_key, text). Timestamps are derived from word counts at seed time,
so topics and action items reference transcript lines by index instead of hard-coded seconds.
"""

PEOPLE: dict[str, tuple[str, str]] = {
    "priya": ("Priya Raman", "priya@lumenlabs.io"),
    "marcus": ("Marcus Chen", "marcus@lumenlabs.io"),
    "sofia": ("Sofia Alvarez", "sofia@lumenlabs.io"),
    "liam": ("Liam Foster", "liam@lumenlabs.io"),
    "daniel": ("Daniel Okafor", "daniel@lumenlabs.io"),
    "emily": ("Emily Park", "emily@lumenlabs.io"),
    "hannah": ("Hannah Lee", "hannah@lumenlabs.io"),
    "ravi": ("Ravi Patel", "ravi@lumenlabs.io"),
    "jordan": ("Jordan Blake", "jordan.blake@brightwave.com"),
    "aisha": ("Aisha Khan", "aisha.khan@brightwave.com"),
    "noah": ("Noah Williams", "noah.williams@gmail.com"),
}

# Demo account for exploring the app without signing up. Matches the "priya" participant by email,
# so her action items show up as "My tasks".
DEMO_ACCOUNT = {
    "name": "Priya Raman",
    "email": "priya@lumenlabs.io",
    "job_title": "Head of Product",
    "password": "demo1234",
}

MEETINGS: list[dict] = [
    {
        "title": "Q4 Product Roadmap Planning",
        "description": "Quarterly planning session to lock the Q4 roadmap and launch dates.",
        "platform": "google_meet",
        "days_ago": 0,
        "time": (9, 30),
        "starred": True,
        "participants": [("priya", "host"), ("marcus", "attendee"), ("sofia", "attendee"), ("liam", "attendee")],
        "transcript": [
            ("priya", "Morning everyone, thanks for joining. The goal today is simple: leave this call with a locked Q4 roadmap and a launch date we all believe in."),
            ("priya", "I shared the draft doc last night. Three big bets are on the table: the analytics dashboard, the Slack integration, and the onboarding revamp."),
            ("marcus", "I read through it. My main concern is capacity. We lose two engineers to the platform migration until mid November, so we realistically have four people for feature work."),
            ("priya", "That's fair. If we had to rank them, where would you put the analytics dashboard?"),
            ("marcus", "First. The data pipeline is already in place from the reporting work last quarter, so most of the effort is the front end and the query layer. I'd estimate five to six weeks."),
            ("sofia", "Design is in good shape there too. We tested the dashboard prototype with eight customers last month and seven of them asked when they could have it."),
            ("liam", "From a marketing angle, the dashboard is the easiest story to tell. Customers can finally see the ROI of the product in one place. I'd love to anchor the November campaign on it."),
            ("priya", "Great, so the dashboard is our anchor. Let's talk about the Slack integration next. Marcus, what does that one look like?"),
            ("marcus", "Slack is smaller than it looks. OAuth, a notification service, and a couple of slash commands. Two engineers for three weeks, but it depends on Slack's app review, which can take up to two weeks on its own."),
            ("liam", "Could we submit for review early, before the integration is feature complete?"),
            ("marcus", "We can submit with the core scopes and add commands later. That's a good idea, it removes the review from the critical path."),
            ("sofia", "I'd want a week to design the message formats. Notifications that are too noisy will get muted, and then the integration is worthless."),
            ("priya", "Agreed. Let's make the Slack integration our second priority and get the app review submitted by the end of October."),
            ("priya", "Which leaves onboarding. Sofia, you've been closest to the research there."),
            ("sofia", "The data is pretty stark. Forty percent of new workspaces never invite a teammate, and those workspaces churn at three times the rate. The onboarding revamp is really about getting that first invite."),
            ("marcus", "That's a strong argument. But it touches the signup flow, billing, and permissions. It's the riskiest of the three by far."),
            ("liam", "What if we split it? A quick win now, like an invite prompt after the first meeting is recorded, and the full revamp in Q1."),
            ("sofia", "I like that. The invite prompt is maybe a week of design and a week of engineering. We can measure the lift before committing to the bigger project."),
            ("priya", "Okay, I'm hearing a clear plan. Dashboard first, Slack second, the invite prompt as a fast experiment, and the full onboarding revamp moves to Q1."),
            ("marcus", "That works for capacity. I'd put the dashboard launch at November eighteenth with a beta the week before."),
            ("liam", "November eighteenth gives me enough time for the launch blog, the email sequence and a webinar. I'll need final screenshots by November fourth."),
            ("sofia", "Screenshots by the fourth is doable as long as we freeze the dashboard layout by the end of October."),
            ("priya", "Let's lock that in then. Design freeze October thirty first, screenshots November fourth, beta November eleventh, launch November eighteenth."),
            ("marcus", "One risk to flag. If the platform migration slips, it eats directly into the dashboard timeline. I'll give a go or no go on the migration by October twentieth."),
            ("priya", "Good, let's track that as our biggest risk. Anything else before we wrap up?"),
            ("liam", "Just that I'd love a short demo video of the dashboard for the beta invite. Even a rough screen recording is fine."),
            ("sofia", "I can record that once the beta build is stable."),
            ("priya", "Perfect. I'll update the roadmap doc and share it with leadership today. Thanks everyone, this was a really productive session."),
        ],
        "topics": [
            {"title": "Capacity and the three Q4 bets", "summary": "Priya frames the three candidates and Marcus flags that only four engineers are available until mid November.", "from": 0, "to": 3},
            {"title": "Analytics dashboard as the anchor", "summary": "Pipeline work is done, prototype testing went well and marketing wants to build the November campaign around it.", "from": 4, "to": 7},
            {"title": "Slack integration and app review", "summary": "Two engineers for three weeks; submitting early for Slack review removes it from the critical path.", "from": 8, "to": 12},
            {"title": "Onboarding: invite prompt experiment", "summary": "Workspaces without invites churn 3x. The team splits the work into a fast invite-prompt experiment now and a Q1 revamp.", "from": 13, "to": 18},
            {"title": "Launch timeline and risks", "summary": "Design freeze Oct 31, screenshots Nov 4, beta Nov 11, launch Nov 18. The platform migration is the main risk.", "from": 19, "to": 27},
        ],
        "summary": {
            "overview": "The team agreed on the Q4 roadmap. The analytics dashboard is the top priority and will launch on November 18, with a beta the week before. The Slack integration is second, and the app review will be submitted early so it doesn't hold up the launch. The onboarding revamp is split: a quick invite-prompt experiment ships this quarter and the full revamp moves to Q1. The biggest risk is the platform migration, which could take engineers away from the dashboard.",
            "bullet_points": [
                "Only four engineers are available for feature work until mid November because of the platform migration.",
                "Analytics dashboard is the Q4 anchor: an estimated 5–6 weeks, and 7 of 8 customers in testing asked for it.",
                "The Slack integration needs about 3 weeks from two engineers. The app review will be submitted with core scopes by the end of October.",
                "40% of new workspaces never invite a teammate and churn at 3x the rate, so an invite prompt will ship as a fast experiment.",
                "Key dates: design freeze Oct 31, screenshots Nov 4, beta Nov 11, launch Nov 18.",
                "Marcus will make a go/no-go call on the platform migration by October 20.",
            ],
            "keywords": ["Roadmap", "Analytics dashboard", "Slack integration", "Onboarding", "Launch timeline", "Capacity"],
        },
        "action_items": [
            {"text": "Update the Q4 roadmap doc and share it with leadership", "assignee": "priya", "due_in_days": 0, "segment": 27},
            {"text": "Submit the Slack app for review with core scopes", "assignee": "marcus", "due_in_days": 21, "segment": 12},
            {"text": "Freeze the analytics dashboard layout", "assignee": "sofia", "due_in_days": 25, "segment": 22},
            {"text": "Make a go/no-go decision on the platform migration", "assignee": "marcus", "due_in_days": 14, "segment": 23},
            {"text": "Draft the launch blog post, email sequence and webinar plan", "assignee": "liam", "due_in_days": 30, "segment": 20},
            {"text": "Record a short dashboard demo video for the beta invite", "assignee": "sofia", "due_in_days": 35, "segment": 26},
        ],
    },
    {
        "title": "Brightwave — Discovery Call",
        "description": "First call with Brightwave's operations team about rolling out Lumen across 120 seats.",
        "platform": "zoom",
        "days_ago": 1,
        "time": (14, 0),
        "starred": False,
        "participants": [("daniel", "host"), ("emily", "attendee"), ("jordan", "attendee"), ("aisha", "attendee")],
        "transcript": [
            ("daniel", "Hi Jordan, hi Aisha, thanks so much for making the time. I'm Daniel, I lead partnerships here, and I've brought along Emily from our customer success team."),
            ("emily", "Hi both, great to meet you. I'll mostly be listening today, but I'll be the person helping you through rollout if we end up working together."),
            ("jordan", "Great to meet you. I run operations at Brightwave and Aisha manages our IT and security reviews, so she'll probably have the harder questions."),
            ("daniel", "Perfect. To start, could you walk me through what prompted you to look at meeting tooling right now?"),
            ("jordan", "Sure. We've grown from forty to about a hundred and twenty people in a year, and our meetings have exploded. Decisions get made on calls and then nobody can find them a week later."),
            ("jordan", "Last month we had two teams build the same feature because the decision to cut one of them was made on a call that half the people missed."),
            ("daniel", "Ouch. That's a story we hear a lot. How are you capturing notes today?"),
            ("jordan", "Honestly, it depends on who's running the meeting. Some people use Google Docs, some people use nothing. There's no single place to look."),
            ("emily", "And when decisions turn into follow-ups, where do those tasks end up?"),
            ("jordan", "Mostly in Asana, if somebody remembers to create them. That's the gap I care most about. Action items get lost between the call and the project tracker."),
            ("daniel", "That's exactly where we focus. Every meeting gets a transcript, a summary and extracted action items with owners, and those can sync into Asana automatically."),
            ("aisha", "Before we go too far, I need to understand data handling. Where are the recordings stored, and who on your side can access them?"),
            ("daniel", "Great question. Everything is stored in AWS in the US region and encrypted at rest and in transit. Our staff can't access customer content without an explicit support grant from an admin."),
            ("aisha", "Do you have a SOC 2 Type II report, and can we control retention?"),
            ("daniel", "Yes to both. I can send the SOC 2 report under NDA today. Admins can set retention anywhere from thirty days to indefinitely, and deletions are permanent."),
            ("aisha", "Good. We'll also need SSO with Okta and the ability to stop the bot from joining external calls with certain customers."),
            ("emily", "Okta SSO is supported on the business plan. For the bot, admins can create rules that skip meetings by domain or by keywords in the title."),
            ("jordan", "That's helpful. What does a typical rollout look like for a team our size?"),
            ("emily", "Usually we start with a pilot of twenty to thirty people for two weeks, ideally a team with lots of meetings, like ops or sales. Then we expand once we've confirmed the workflows."),
            ("jordan", "I'd want the ops leads in the pilot. They're in back-to-back calls all day and they're the loudest about lost decisions."),
            ("daniel", "That sounds like a great pilot group. On pricing, for a hundred and twenty seats on the business plan we'd be looking at an annual agreement. I'll put together a proposal with pilot terms."),
            ("jordan", "Please do. Our budget cycle closes at the end of November, so if this is going to happen this year we need a decision by then."),
            ("aisha", "And I'll need about two weeks for the security review once I have the documentation."),
            ("daniel", "Understood. So the plan is: I send the SOC 2 report and the security questionnaire today, Emily drafts a pilot plan for your ops leads, and I send the proposal by Friday."),
            ("jordan", "That works. Let's also book a follow-up for next Thursday to go through the pilot plan together."),
            ("daniel", "Perfect, I'll send the invite. Thanks again Jordan and Aisha, really appreciate your time."),
        ],
        "topics": [
            {"title": "Introductions", "summary": "Daniel and Emily introduce themselves. Jordan runs operations at Brightwave and Aisha runs IT and security.", "from": 0, "to": 3},
            {"title": "Pain points: lost decisions and tasks", "summary": "Brightwave tripled its headcount. Decisions made on calls get lost, and action items don't reach Asana.", "from": 4, "to": 10},
            {"title": "Security, compliance and admin controls", "summary": "Covers storage, encryption, SOC 2 Type II, retention controls, Okta SSO and bot rules for external calls.", "from": 11, "to": 16},
            {"title": "Pilot, pricing and next steps", "summary": "A two-week pilot with the ops leads, an annual business plan proposal, and a decision before the November budget close.", "from": 17, "to": 25},
        ],
        "summary": {
            "overview": "Brightwave has grown to 120 people. They are losing track of decisions and action items made in meetings, and notes are kept inconsistently across teams. Jordan's top priority is getting action items into Asana reliably. Aisha needs SOC 2 documentation, retention controls, Okta SSO and bot rules for external calls, and will need two weeks for a security review. Both sides agreed on a two-week pilot with the ops leads. Brightwave needs a decision before its budget closes at the end of November.",
            "bullet_points": [
                "Brightwave grew from 40 to 120 people in a year. Two teams recently built the same feature because a decision was missed.",
                "Notes are kept inconsistently (Google Docs or nothing), and action items often never reach Asana.",
                "Security requirements: SOC 2 Type II, configurable retention, Okta SSO, and rules to skip external meetings.",
                "Proposed pilot: 20–30 ops leads for two weeks before a company-wide rollout.",
                "Budget closes at the end of November, and the security review needs about two weeks.",
            ],
            "keywords": ["Discovery", "Asana", "SOC 2", "Okta SSO", "Pilot", "Budget"],
        },
        "action_items": [
            {"text": "Send the SOC 2 Type II report (under NDA) and the security questionnaire to Aisha", "assignee": "daniel", "due_in_days": 0, "segment": 23, "done": True},
            {"text": "Draft a two-week pilot plan for the Brightwave ops leads", "assignee": "emily", "due_in_days": 3, "segment": 23},
            {"text": "Send the 120-seat business plan proposal with pilot terms", "assignee": "daniel", "due_in_days": 3, "segment": 20},
            {"text": "Schedule a follow-up call for next Thursday to review the pilot plan", "assignee": "daniel", "due_in_days": 1, "segment": 24, "done": True},
            {"text": "Complete the security review once documentation is received", "assignee": "aisha", "due_in_days": 16, "segment": 22},
        ],
    },
    {
        "title": "Weekly Engineering Standup",
        "description": "Weekly sync on sprint progress, blockers and the platform migration.",
        "platform": "microsoft_teams",
        "days_ago": 2,
        "time": (10, 0),
        "starred": False,
        "participants": [("marcus", "host"), ("hannah", "attendee"), ("ravi", "attendee"), ("priya", "attendee")],
        "transcript": [
            ("marcus", "Alright, let's get started. Same format as usual: what you shipped, what's next, and any blockers. Hannah, want to kick us off?"),
            ("hannah", "Sure. I finished the query layer for the analytics dashboard. Aggregations for meeting volume and talk time are working, and the endpoints are behind a feature flag in staging."),
            ("hannah", "Next I'm on the date range filters and caching. The weekly rollups are slow for big workspaces, around four seconds, so I want to precompute them."),
            ("marcus", "Four seconds is too slow for a dashboard. Precomputing makes sense. Do you need anything from infra for that?"),
            ("hannah", "Probably a scheduled job runner. I was going to use the existing worker queue, but I'd like Ravi to sanity check the load."),
            ("ravi", "Happy to. The queue has plenty of headroom at the moment, but let's not schedule all workspaces at exactly midnight. We should spread the jobs out."),
            ("marcus", "Good call. Ravi, how's the migration going?"),
            ("ravi", "Mostly on track. We've moved seventy percent of the services to the new cluster. The remaining ones are the transcription workers and the webhook service."),
            ("ravi", "The blocker is the webhook service. It relies on sticky sessions, and the new load balancer handles them differently. I've seen dropped events in the canary."),
            ("priya", "How many events are we talking about? Is any customer impact visible yet?"),
            ("ravi", "Under half a percent, and only on the canary, which handles about five percent of traffic. No customer reports so far, but I don't want to roll it forward until it's fixed."),
            ("marcus", "Agreed, hold the rollout. Can we remove the sticky session dependency altogether?"),
            ("ravi", "Yes, we can move delivery state into Redis. That's maybe three days of work, and it's cleaner long term anyway."),
            ("marcus", "Let's do that. Priya, this probably affects the October twentieth go/no-go we discussed."),
            ("priya", "It's fine if it's three days. Just flag it early if it starts looking like more than a week, because the dashboard timeline depends on getting people back."),
            ("ravi", "Will do. I'll post an update in the migration channel on Thursday either way."),
            ("marcus", "On my side, I reviewed the Slack integration spike. OAuth is working end to end and I've started on the notification service. I'll prepare the app review submission next week."),
            ("marcus", "One more thing: on-call. Hannah, you're on this week. Remember the new runbook is in the wiki, and please page me if the webhook alerts fire."),
            ("hannah", "Got it. Will do."),
            ("priya", "Quick product note from me. Design shared updated dashboard mocks yesterday. The main change is a talk-time chart per speaker, which Hannah's endpoints should already support."),
            ("hannah", "They do. Talk time per speaker is one of the aggregations, so that should be straightforward."),
            ("marcus", "Great. Let's wrap there. Ravi on Redis delivery state, Hannah on precomputed rollups, and I'll keep moving on Slack. Thanks everyone."),
        ],
        "topics": [
            {"title": "Analytics query layer progress", "summary": "The query layer is done and behind a flag. Weekly rollups take about 4s, so they will be precomputed on the worker queue with staggered jobs.", "from": 0, "to": 5},
            {"title": "Platform migration blocker", "summary": "70% of services are migrated. Sticky sessions cause dropped webhook events in the canary, so delivery state will move to Redis.", "from": 6, "to": 15},
            {"title": "Slack integration and on-call", "summary": "Slack OAuth is working, notification service started; Hannah is on call with the new runbook.", "from": 16, "to": 18},
            {"title": "Dashboard design update", "summary": "The new mocks add a talk-time chart per speaker, which the existing endpoints already support.", "from": 19, "to": 21},
        ],
        "summary": {
            "overview": "The analytics query layer is complete and in staging behind a feature flag. Weekly rollups for large workspaces take about four seconds, so they will be precomputed with staggered jobs. The platform migration is 70% done, but the webhook service drops events in the canary because of sticky sessions. The rollout is on hold while delivery state moves to Redis, which should take about three days. Slack OAuth is working end to end.",
            "bullet_points": [
                "The analytics endpoints are behind a feature flag in staging. Date filters and caching are next.",
                "Weekly rollups will be precomputed on the existing worker queue, with jobs staggered to avoid load spikes.",
                "The migration is 70% complete. The webhook service drops under 0.5% of events in the canary.",
                "The rollout is on hold. Moving delivery state to Redis should take about 3 days.",
                "Slack OAuth works end to end, and the app review submission is next week.",
                "The dashboard mocks now include a talk-time chart per speaker.",
            ],
            "keywords": ["Standup", "Analytics", "Migration", "Webhooks", "Redis", "On-call"],
        },
        "action_items": [
            {"text": "Move webhook delivery state into Redis to remove sticky sessions", "assignee": "ravi", "due_in_days": 1, "segment": 12},
            {"text": "Post a migration status update in the channel on Thursday", "assignee": "ravi", "due_in_days": 0, "segment": 15, "done": True},
            {"text": "Precompute weekly analytics rollups with staggered jobs", "assignee": "hannah", "due_in_days": 5, "segment": 2},
            {"text": "Prepare the Slack app review submission", "assignee": "marcus", "due_in_days": 5, "segment": 16},
        ],
    },
    {
        "title": "Website Redesign Kickoff",
        "description": "Kickoff for the marketing site redesign: goals, scope and timeline.",
        "platform": "zoom",
        "days_ago": 6,
        "time": (16, 0),
        "starred": True,
        "participants": [("sofia", "host"), ("liam", "attendee"), ("priya", "attendee")],
        "transcript": [
            ("sofia", "Thanks for joining, this is the kickoff for the website redesign. I want to agree on goals, scope and a rough timeline today, and leave the visual exploration for next week."),
            ("liam", "Let me start with the why. Our homepage converts at one point two percent. The benchmark for our category is closer to three. And the site still describes the product we had two years ago."),
            ("priya", "Right. We talk a lot about transcription, but customers buy us for the summaries and action items now. The site needs to lead with outcomes."),
            ("sofia", "So the primary goal is conversion, and the secondary goal is positioning. Anything else?"),
            ("liam", "Page speed. We're at about four seconds to largest contentful paint on mobile, which hurts both conversions and SEO."),
            ("sofia", "Okay. Three goals: conversion, positioning and performance. Let's talk scope. My proposal is the homepage, pricing page and three product pages, plus a new component library we can reuse."),
            ("liam", "I'd add a customer stories page. Social proof is the biggest gap we have. Prospects keep asking who else like them uses us."),
            ("priya", "Agreed, but let's keep the blog and docs out of scope. They're on a different system and would double the work."),
            ("sofia", "Fine by me. Homepage, pricing, three product pages and customer stories. Blog and docs are out."),
            ("liam", "For customer stories, I can line up three customers. Brightwave might even be one if the pilot goes well."),
            ("priya", "Let's not count on Brightwave yet, they're still in discovery. I'd go with the two agencies and the healthcare customer we already have quotes from."),
            ("sofia", "On the process, I'd like to run a short round of five customer interviews about how they describe us before we write any copy."),
            ("liam", "Love that. If we can use their language in the headlines, we'll convert better. I can help recruit from our power users."),
            ("sofia", "Timeline: interviews and messaging in two weeks, design in three weeks, build in four. So we're looking at about nine weeks, landing mid January."),
            ("priya", "That works, as long as it doesn't pull Sofia away from the dashboard launch in November. Can we bring in a contractor for the build?"),
            ("liam", "I have budget for a contractor. I'll get a couple of quotes from the agencies we've used before."),
            ("sofia", "Great. I'll write up the brief with the goals, scope and timeline, and share a moodboard next week so we can align on the visual direction."),
            ("priya", "Sounds good. Let's make sure we have a baseline of the current metrics before we start, so we can measure the impact properly."),
            ("liam", "I'll pull conversion, bounce and page speed baselines from analytics this week."),
            ("sofia", "Perfect, thanks both. Great kickoff."),
        ],
        "topics": [
            {"title": "Why redesign now", "summary": "Homepage conversion is 1.2% against a 3% benchmark, and the site describes an outdated product.", "from": 0, "to": 4},
            {"title": "Scope", "summary": "In scope: the homepage, pricing, three product pages, customer stories and a component library. The blog and docs are out.", "from": 5, "to": 10},
            {"title": "Process and timeline", "summary": "Five customer interviews first, then about 9 weeks to a mid-January launch, with a contractor for the build.", "from": 11, "to": 19},
        ],
        "summary": {
            "overview": "The team kicked off the website redesign with three goals: raise homepage conversion from 1.2% toward the 3% category benchmark, reposition the product around summaries and action items, and fix mobile page speed. The scope covers the homepage, pricing, three product pages, a new customer stories page and a reusable component library. The blog and docs are out of scope. Five customer interviews will shape the messaging. The work should take about nine weeks, with a contractor handling the build so Sofia can stay focused on the dashboard launch.",
            "bullet_points": [
                "Goals: conversion (1.2% → closer to 3%), positioning around outcomes, and mobile performance (LCP is about 4s).",
                "Scope: homepage, pricing, three product pages, customer stories and a component library. Blog and docs are out.",
                "Customer stories will use the two agencies and the healthcare customer. Brightwave is not confirmed yet.",
                "Five customer interviews come before copywriting so the headlines use customers' own language.",
                "Timeline: 2 weeks of messaging, 3 weeks of design and 4 weeks of build, landing in mid January.",
            ],
            "keywords": ["Website", "Conversion", "Positioning", "Customer stories", "Page speed", "Timeline"],
        },
        "action_items": [
            {"text": "Write the redesign brief with goals, scope and timeline", "assignee": "sofia", "due_in_days": -2, "segment": 16, "done": True},
            {"text": "Share a moodboard for visual direction", "assignee": "sofia", "due_in_days": 1, "segment": 16},
            {"text": "Get quotes from contract development agencies", "assignee": "liam", "due_in_days": 4, "segment": 15},
            {"text": "Pull baseline conversion, bounce and page speed metrics", "assignee": "liam", "due_in_days": -1, "segment": 18, "done": True},
            {"text": "Recruit five power users for messaging interviews", "assignee": "liam", "due_in_days": 2, "segment": 12},
        ],
    },
    {
        "title": "Interview: Senior Frontend Engineer — Noah Williams",
        "description": "Technical interview for the Senior Frontend Engineer role.",
        "platform": "google_meet",
        "days_ago": 9,
        "time": (11, 0),
        "starred": False,
        "participants": [("marcus", "host"), ("sofia", "attendee"), ("noah", "attendee")],
        "transcript": [
            ("marcus", "Hi Noah, thanks for joining. I'm Marcus, I lead engineering, and this is Sofia, who leads design. We'll spend about forty minutes together and leave time for your questions at the end."),
            ("noah", "Thanks for having me. Excited to chat."),
            ("marcus", "To start, could you tell us about a frontend project you're proud of and what your role was?"),
            ("noah", "Sure. At my current company I led the rebuild of our analytics product in React and TypeScript. The old version rendered huge tables on the client and would freeze on large accounts."),
            ("noah", "We moved aggregation to the server, virtualized the tables and introduced a small charting layer on top of D3. Load time on our largest accounts went from about twelve seconds to under two."),
            ("marcus", "Nice. How did you decide what to move to the server versus keep on the client?"),
            ("noah", "Mostly by asking which interactions needed to feel instant. Sorting and filtering a visible page stayed on the client. Anything that touched the full dataset moved to the server, and we cached the common queries."),
            ("sofia", "I'm curious how you worked with design on that project. Were there tradeoffs you had to push back on?"),
            ("noah", "Definitely. The original design had live-updating charts everywhere, which would have hammered the API. I built a quick prototype to show the cost, and we agreed on refreshing on focus plus a manual refresh button."),
            ("sofia", "That's a nice way to handle it. Showing instead of telling."),
            ("marcus", "Let's do a short design exercise. Imagine a meeting page with a video player and a transcript. When the video plays, the current sentence should highlight, and clicking a sentence should jump the video. How would you build it?"),
            ("noah", "I'd keep the player as the source of truth for the current time and expose it through a small store or context. The transcript subscribes to it and finds the active segment with a binary search, since segments are sorted by start time."),
            ("noah", "Clicking a segment just calls seek on the player. For performance, I'd only re-render the segment whose active state changed, and auto-scroll it into view unless the user has scrolled manually recently."),
            ("marcus", "How would you handle search within the transcript?"),
            ("noah", "Highlight matches inline, show a count, and let you step through results with next and previous. I'd debounce the input and escape the query so special characters don't break the regex."),
            ("sofia", "And accessibility? Transcripts can get long."),
            ("noah", "Each segment would be a button with the timestamp in its label, the active segment would use aria-current, and I'd make sure the auto-scroll respects reduced motion preferences."),
            ("marcus", "Great answers. We have a few minutes left. What questions do you have for us?"),
            ("noah", "How do engineering and design split ownership of the design system? And what does the on-call rotation look like for frontend engineers?"),
            ("sofia", "Design owns the tokens and the Figma library, and engineering owns the component code. We pair on anything new. It works well, though documentation is our weak spot."),
            ("marcus", "Frontend engineers join the on-call rotation about once every six weeks, mostly for alerts on the web app. There's a runbook and a secondary on-call for backup."),
            ("noah", "That sounds reasonable. Thanks, this was a fun conversation."),
            ("marcus", "Thanks Noah. Our recruiter will be in touch within a few days about next steps."),
        ],
        "topics": [
            {"title": "Introductions and background", "summary": "Noah describes rebuilding an analytics product: server-side aggregation and virtualized tables brought load time from 12s to under 2s.", "from": 0, "to": 6},
            {"title": "Collaborating with design", "summary": "Noah used a prototype to show the cost of live-updating charts and agreed on refresh-on-focus instead.", "from": 7, "to": 9},
            {"title": "System design: synced transcript player", "summary": "The player is the source of truth. The active segment is found by binary search, with click-to-seek, inline search highlighting and accessible markup.", "from": 10, "to": 16},
            {"title": "Candidate questions", "summary": "Ownership of the design system and how the frontend on-call rotation works.", "from": 17, "to": 22},
        ],
        "summary": {
            "overview": "Noah Williams interviewed for the Senior Frontend Engineer role. He described leading the rebuild of an analytics product, where server-side aggregation and virtualized tables cut load times from 12 seconds to under 2. He gave a strong design answer for a synced transcript and video player: the player owns the current time, the active segment is found by binary search, clicking a segment seeks the player, and search, highlighting and accessibility were all handled carefully. Both interviewers were positive about his communication and how he works with design.",
            "bullet_points": [
                "Led a React/TypeScript rebuild of an analytics product, cutting load time from about 12s to under 2s.",
                "Splits work by what needs to feel instant: client-side for the visible page, server-side for full-dataset operations.",
                "Pushed back on a costly design with a prototype instead of an argument.",
                "Transcript sync design: player as the source of truth, binary search for the active segment, minimal re-renders.",
                "Covered accessibility: buttons for segments, aria-current, and reduced-motion-aware scrolling.",
            ],
            "keywords": ["Interview", "Frontend", "React", "Performance", "System design", "Accessibility"],
        },
        "action_items": [
            {"text": "Submit interview scorecard for Noah Williams", "assignee": "marcus", "due_in_days": -8, "segment": 22, "done": True},
            {"text": "Submit design collaboration feedback for Noah Williams", "assignee": "sofia", "due_in_days": -8, "segment": 22},
            {"text": "Document design system ownership and contribution process", "assignee": "sofia", "due_in_days": 10, "segment": 19},
        ],
    },
]
