"use client";

import { FileText, Loader2, Pencil, RefreshCw, Sparkles } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { toast } from "sonner";

import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { EmptyState } from "@/components/common/empty-state";
import { ParticipantAvatar } from "@/components/common/participant-avatar";
import { Button } from "@/components/ui/button";
import { api } from "@/lib/api";
import { formatDate } from "@/lib/format";
import { speakerColor } from "@/lib/speakers";
import type { MeetingDetail, Summary } from "@/types/api";

import { SummaryDialog } from "./summary-dialog";

export function NotesSection({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) {
  return (
    <section className="py-5 first:pt-1">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-sm font-semibold text-gray-900">{title}</h3>
        {action}
      </div>
      {children}
    </section>
  );
}

/** Share of total speaking time per participant, computed from transcript segments. */
function SpeakerTalkTime({ meeting }: { meeting: MeetingDetail }) {
  const rows = useMemo(() => {
    const totals = new Map<number, number>();
    for (const s of meeting.segments) {
      if (s.speaker_id != null) totals.set(s.speaker_id, (totals.get(s.speaker_id) ?? 0) + (s.end_time - s.start_time));
    }
    const sum = [...totals.values()].reduce((a, b) => a + b, 0) || 1;
    return meeting.participants
      .map((p) => ({ person: p, share: (totals.get(p.id) ?? 0) / sum }))
      .sort((a, b) => b.share - a.share);
  }, [meeting]);

  return (
    <ul className="grid gap-3">
      {rows.map(({ person, share }) => (
        <li key={person.id} className="flex items-center gap-3">
          <ParticipantAvatar participant={person} size="sm" />
          <span className="w-32 truncate text-sm text-gray-700">{person.name}</span>
          <span className="h-1.5 flex-1 overflow-hidden rounded-full bg-gray-100">
            <span className={`block h-full rounded-full ${speakerColor(person.id).bar}`} style={{ width: `${share * 100}%` }} />
          </span>
          <span className="w-10 text-right text-xs text-gray-500 tabular-nums">{Math.round(share * 100)}%</span>
        </li>
      ))}
    </ul>
  );
}

interface SummaryPanelProps {
  meeting: MeetingDetail;
  onSummaryChange: (summary: Summary) => void;
  /** Receives the whole meeting after notes are generated (summary, outline and possibly action items change). */
  onMeetingChange: (meeting: MeetingDetail) => void;
}

export function SummaryPanel({ meeting, onSummaryChange, onMeetingChange }: SummaryPanelProps) {
  const [editing, setEditing] = useState(false);
  const [confirmRegenerate, setConfirmRegenerate] = useState(false);
  const [generating, setGenerating] = useState(false);
  const { summary } = meeting;
  const hasContent = !!summary && (summary.overview || summary.bullet_points.length || summary.keywords.length);
  const hasTranscript = meeting.segments.length > 0;

  const generate = async () => {
    setGenerating(true);
    try {
      const updated = await api.meetings.generateNotes(meeting.id);
      onMeetingChange(updated);
      const added = updated.action_items.length - meeting.action_items.length;
      toast.success("AI notes generated", {
        description: [
          `${updated.topics.length} chapter${updated.topics.length === 1 ? "" : "s"}`,
          added > 0 && `${added} action item${added === 1 ? "" : "s"}`,
        ]
          .filter(Boolean)
          .join(" · "),
      });
    } catch (error) {
      toast.error((error as Error).message);
      throw error;
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="divide-y">
      {hasContent ? (
        <>
          <div className="flex items-center justify-between pb-3">
            <span className="flex items-center gap-1.5 text-xs font-medium text-brand-600">
              <Sparkles className="size-3.5" /> Generated by Hersheys AI · updated {formatDate(summary.updated_at)}
            </span>
            <div className="flex gap-1">
              {hasTranscript && (
                <Button variant="ghost" size="sm" onClick={() => setConfirmRegenerate(true)} className="text-gray-600">
                  <RefreshCw /> Regenerate
                </Button>
              )}
              <Button variant="ghost" size="sm" onClick={() => setEditing(true)} className="text-gray-600">
                <Pencil /> Edit
              </Button>
            </div>
          </div>

          {summary.keywords.length > 0 && (
            <NotesSection title="Keywords">
              <div className="flex flex-wrap gap-1.5">
                {summary.keywords.map((k) => (
                  <span key={k} className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-medium text-brand-700 ring-1 ring-brand-100">
                    {k}
                  </span>
                ))}
              </div>
            </NotesSection>
          )}

          {summary.overview && (
            <NotesSection title="Overview">
              <p className="text-sm leading-relaxed whitespace-pre-line text-gray-700">{summary.overview}</p>
            </NotesSection>
          )}

          {summary.bullet_points.length > 0 && (
            <NotesSection title="Notes">
              <ul className="grid gap-2">
                {summary.bullet_points.map((point, i) => (
                  <li key={i} className="flex gap-2.5 text-sm leading-relaxed text-gray-700">
                    <span className="mt-2 size-1.5 shrink-0 rounded-full bg-brand-400" />
                    {point}
                  </li>
                ))}
              </ul>
            </NotesSection>
          )}
        </>
      ) : (
        <EmptyState
          icon={FileText}
          title="No AI notes yet"
          description={
            hasTranscript
              ? "Generate a summary, keywords, chapters and action items from this meeting's transcript, or write the notes yourself."
              : "This meeting has no transcript to summarize. You can write the notes yourself."
          }
          action={
            <div className="flex flex-wrap justify-center gap-2">
              {hasTranscript && (
                <Button onClick={() => generate().catch(() => undefined)} disabled={generating}>
                  {generating ? <Loader2 className="animate-spin" /> : <Sparkles />}
                  {generating ? "Generating…" : "Generate notes"}
                </Button>
              )}
              <Button variant={hasTranscript ? "outline" : "default"} onClick={() => setEditing(true)}>
                <Pencil /> Write notes
              </Button>
            </div>
          }
        />
      )}

      {meeting.participants.length > 0 && meeting.segments.length > 0 && (
        <NotesSection title="Speaker talk time">
          <SpeakerTalkTime meeting={meeting} />
        </NotesSection>
      )}

      <ConfirmDialog
        open={confirmRegenerate}
        onOpenChange={setConfirmRegenerate}
        tone="primary"
        title="Regenerate AI notes?"
        description="The overview, notes, keywords and outline will be rebuilt from the transcript, replacing any edits. Existing action items are kept."
        confirmLabel="Regenerate"
        busyLabel="Generating…"
        onConfirm={generate}
      />

      <SummaryDialog
        open={editing}
        onOpenChange={setEditing}
        meetingId={meeting.id}
        summary={summary}
        onSaved={onSummaryChange}
      />
    </div>
  );
}
